name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["18"]
                os: [ubuntu-latest, macOS-latest, windows-latest]
        name: node.js ${{ matrix.node }} test in ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Environment
              run: |
                  npm install pnpm -g
                  node -v
                  npm -v
                  pnpm -v

            - name: Install
              run: pnpm install

            - name: Compiler
              run: yarn build

            - name: Tester
              run: yarn test
