name: Changesets
on:
    push:
        branches:
            - main
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
defaults:
    run:
        shell: bash
jobs:
    version:
        timeout-minutes: 15
        if: ${{ github.repository_owner == 'axetroy' }}
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: install pnpm
              run: npm i pnpm@latest -g

            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER

            - name: install dependencies
              run: pnpm install

            - name: create and publish versions
              id: changesets
              uses: changesets/action@v1
              with:
                  version: pnpm changeset:version
                  publish: pnpm changeset:release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
